#!/usr/bin/env bash

source /opt/conda/etc/profile.d/conda.sh
conda activate smartspim_stitch

# Creates the SmartSPIM BigStitcher XML
big_stitcher_json=$(python run_capsule.py)

conda deactivate

# echo "Captured Output: $big_stitcher_json"
python -m aind_exaspim_pipeline_utils.imagej_wrapper --input_json $big_stitcher_json --log_level="DEBUG"